TredaFront/TredaFront/Controllers/ForStoreController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TredaFront.Models;

namespace TredaFront.Controllers
{
    public class ForStoreController : Controller
    {
        // GET: ForStore
        public ViewResult Index() => View();
        [HttpPost]
        public async Task<ActionResult> Index(int id)
        {
            List<ForStore> store = new List<ForStore>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44313/api/ForStore/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    store = JsonConvert.DeserializeObject<List<ForStore>>(apiResponse);
                }
            }
            return View(store);

        }
    }
}

TredaFront/TredaFront/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="http://localhost:56345/">
            <img src="~/Images/Mark.png" alt="logo" style="width:40px;" />
        </a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a class="nav-item nav-link">@Html.ActionLink("Inicio", "Index", "Home")</a>
                <a class="nav-item nav-link">@Html.ActionLink("Stores", "IndexS", "Stores")</a>
                <a class="nav-item nav-link">@Html.ActionLink("Products", "IndexP", "Products")</a>
                <a class="nav-item nav-link">@Html.ActionLink("Products For Store", "Index", "ForStore")</a>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
</body>
</html>